import type { Metadata } from "next";
import Navbar from "@/sections/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <div className="container mx-auto max-w-7xl">
          <Navbar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
